# Generated by Django 3.2.4 on 2021-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilink_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
