# Generated by Django 3.2.4 on 2021-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilink_app', '0002_auto_20210731_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='host_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
