# Generated by Django 3.2.4 on 2021-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilink_app', '0004_auto_20210806_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicollection',
            name='public',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
